name: Actions Workflow

on:
  - push
  - pull_request

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Github variables
        run: |
          echo "Github commit sha:"
          echo $GITHUB_SHA
          echo "Github repository (username/repository)"
          echo $GITHUB_REPOSITORY
          echo "Github workspace"
          echo $GITHUB_WORKSPACE
          echo "Github token, blurred if printed"
          echo "${{ github.token }}"
      - name: List Files Pre Checkout
        shell: bash
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files Post Checkout
        shell: bash
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: "actions/hello-world-javascript-action@v1.1"
        with:
          who-to-greet: Test
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
